# -- Site Configuration --

defaultContentLanguage: "en"
baseURL: "https://example.org/"
enableRobotsTXT: true
paginate: 15
summaryLength: 0
enableEmoji: true

outputs:
  home: ["HTML", "RSS", "searchindex"]

outputFormats:
  searchindex:
    mediaType: "application/json"
    baseName: "index"
    isPlainText: true
    notAlternative: true

module:
  imports:
    - path: "github.com/omegion/hugo-omegion"
